const actions = {
  UPDATE_GRID_COORDS: 'UPDATE_GRID_COORDS',
  UPDATE_WINDOW_WIDTH: 'UPDATE_WINDOW_WIDTH',
  OPEN_MODAL: 'SHOW_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  UPDATE_X_Y_COORDS: 'UPDATE_X_Y_COORDS',
  UPDATE_ACTIVE: 'UPDATE_ACTIVE',
  RESET_ACTIVE: 'RESET_ACTIVE',
};

export default actions;
